config/routes.rb
Rails.application.routes.draw do

	root   'main#index'
	get    'main/index'
	get    'index'	      => 'main#index'
	get    'help'	        => 'main#help'
	get    'about'	      => 'main#about'
	get    'contact'      => 'main#contact'
	get    'battle'       => 'main#battle'
	post   'send_contact' => 'main#send_contact'
	get    'signup'	      => 'users#new'
	get    'login'	      => 'sessions#new'
	post   'login'	      => 'sessions#create'
	delete 'logout'	      => 'sessions#destroy'
	resources :users
	resources :weapons
	resources :skills
	resources :npcs
	resources :parties
	resources :weapon_categories

	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :npcs do
		resources :skills,      only: :index,   as: :skills
		resources :npc_weapons, only: :destroy, as: :equipments
	end
	resources :parties do
		resources :npcs,       only: :index,             as: :npcs
		resources :party_npcs, only: [:index, :destroy], as: :members
	end
	resources :relationships, only: [:create, :destroy]

end

app/models/party.rb
class Party < ActiveRecord::Base
	belongs_to :user
	has_many :members, class_name: "PartyNpc", inverse_of: :party, 
		:dependent => :destroy 
	has_many :npcs, through: :members
	has_many :activity_feeds
	accepts_nested_attributes_for :members, :allow_destroy => true
	validates :title, presence: true, length: { maximum: 50 }

	def reject_party_npcs(attributed)
		attributed['id'].blank?
	end

	def filter_npcs
		Npc.all_active
	end

	def self.all_active
		all.where(deleted: false)
	end

	def build_members
		self.members.build.amount = 1 unless !self.members.empty?
	end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
	before_action :set_party, only: [:show, :edit, :update, :destroy]
	before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
	before_action :correct_user,	 only: [:edit, :update, :destroy]

	def index
		@parties = Party.all_active
	end

	def show
	end

	def new
		@party = Party.new
		@party.build_members
	end

	def create
		@party = Party.new(party_params)
		@party.user = current_user
		if @party.save
			current_user.generate_feed(party: @party, feed_type: 'insertion')
			flash.now[:success] = "Informações Salvas"
			redirect_to @party and return
		else
			flash.now[:danger] = "Ooops! Algo deu errado..."
		end
		render :action => 'new'
	end

	def edit
	end

	def update
		# save goes like usual
		if @party.update_attributes(party_params)
			flash.now[:success] = "Informações atualizadas"
			current_user.generate_feed(party: @party, feed_type: 'updated')
			redirect_to @party and return
		else
			flash.now[:danger] = "Ooops! Algo deu errado..."
		end
		render :action => 'edit'
	end

	def destroy
		current_user.generate_feed(party: @party, feed_type: 'destroyed')
		@party.update(deleted: true, deleted_at: Time.zone.now)
		flash.now[:success] = "Operação concluída com sucesso!"
		redirect_to parties_url
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_party
			@party = Party.find(params[:id])
		end

		def party_params
			params.require(:party).permit(:title, 
									members_attributes: [:npc_id, :amount, :_destroy, :id])
		end

		# Before filters

		# Confirms a logged-in user.
		def logged_in_user
			unless logged_in?
				store_location
				flash.now[:danger] = "Acesse o sistema para efetuar esta operação"
				redirect_to login_url
			end
		end

		# Confirms the correct user.
		def correct_user
			@party = Party.find(params[:id])
			redirect_to(root_url) unless current_user?(@party.user) || admin?
		end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<%= form_for(@party, class: 'form-horizontal') do |f| %>
	<div class="col-md-12 col-thin">
		<div class="form-group">
			<%= render partial: 'shared/error_messages', locals: {object: @party} %>
		</div>
	</div>

	<div class="col-md-12 col-thin">
		<div class="form-group">
			<%= f.label :title, "Titulo" %>
			<%= f.text_field :title, class: 'form-control input-sm' %>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h5>NPCS</h5>
			</div>

			<div class="table-responsive">
				<table id="members" class="table table-condensed">
					<thead>
						<tr>
							<th width="85%" colspan="2">Membro</th>
							<th width="15%">Quantidade</th>
						</tr>
					</thead>
					<tbody>
						<%= f.fields_for :members, @party.members do |ff| %>
							<tr class="duplicatable">
								<%= ff.hidden_field :id, class: 'nested_id' %>
								<td align="center">
									<% if ff.object.new_record? %>
										<%= link_to '', class: 'btn btn-danger btn-xs destroy_dup', 
																															remote: true do %>
											<%= link_icon('minus') %>
										<% end %>
									<% else %>
										<%= link_to party_member_path(@party, ff.object), 
															method: :delete, remote: true, 
															class: 'btn btn-danger btn-xs destroy_dup' do %>
											<%= link_icon('minus') %>
										<% end %>
									<% end %>
								</td>
								<td width="80%">
									<%= ff.collection_select :npc_id, @party.filter_npcs, 
												:id, :name, {}, class: "form-control input-sm" %>
								</td>
								<td width="15%">
									<%= ff.number_field :amount, class: "form-control input-sm" %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>

			<div class="panel-footer">
				<%= link_to '', class: 'btn btn-info btn-xs duplicate' do %>
					<%= link_icon('plus') %> Adicionar
				<% end %>
			</div>
		</div>
	</div>

	<div class="col-md-12 col-thin">
		<div class="form-group">
			<%= button_tag yield(:button_text),	type: :submit, 
																					class: "btn btn-default btn-sm" %>
		</div>
	</div>
<% end %>

app/views/parties/_npc.html.erb
<% ally_class = party_npc.npc.ally ? 'info' : 'danger' %>
<% perc_attr_index = (party_npc.npc.attr_index*100) / 12 %>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h6>
				<b class="text-<%= ally_class %>">
					<span class="badge">
						<%= party_npc.npc.id %>
					</span> <%= party_npc.npc.name %> 
					<span class="pull-right">
						</span> <%= party_npc.amount %> 
					</span>
				</b>
			</h6>
		</div>

		<% if !party_npc.npc.img_url.empty? %>
			<%= link_to npc do %>
				<%= image_tag party_npc.npc.img_url, size: "300", class: "img-thumbnail" %>
			<% end %>
		<% end %>

		<ul class="list-group">
			<li class="list-group-item">
				<b>Indice de Atributo</b>
				<div class="progress">
					<div class="progress-bar progress-bar-<%= ally_class %>" 
							role="progressbar" aria-valuemin="0" aria-valuemax="12" 
							aria-valuenow="<%= party_npc.npc.attr_index %>"
						 	style="width: <%= perc_attr_index %>%;">
						<%= party_npc.npc.attr_index %>
					</div>
				</div>
			</li>
		</ul>

		<div class="panel-footer">
			<%= link_to npc, title: "Visualizar", 
														class: "btn btn-default btn-xs" do %>
				<%= link_icon "new-window","Visualizar" %>
			<% end %>
			<% if party_npc.npc.user == current_user %>
				<div class="pull-right">
					<%= link_to edit_npc_path(npc), title: "Editar", 
										class: "btn btn-primary btn-xs" do %>
						<span class="glyphicon glyphicon-edit"></span>
					<% end %>
					<%= link_to(npc, method: :delete, title: "Remover", 
										class: "btn btn-danger btn-xs", 
										data: { confirm: "Deseja remover?" }) do %>
						<span class="glyphicon glyphicon-remove"></span>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/parties/_party.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h5>
				<b>
					<%= link_to party do %>
						<span class="badge"><%= party.id %></span> <%= party.title %>
					<% end %>
				</b>
			</h5>
		</div>

		<ul class="list-group">
			<li class="list-group-item">
				<b>Membros </b>
				<span class="badge"><%= party.members.sum(:amount) %></span>
			</li>
			<li class="list-group-item">
				<b>Tipos de NPC </b>
				<span class="badge"><%= party.members.count(:npc_id) %></span>
			</li>
		</ul>

		<div class="panel-footer">
			<%= link_to party, title: "Visualizar", 
								class: "btn btn-default btn-xs" do %>
				<span class="glyphicon glyphicon-new-window"></span> Visualizar
			<% end %>
			<% if current_user?(party.user) || admin? %>
				<div class="pull-right">
					<%= link_to edit_party_path(party), title: "Editar", 
										class: "btn btn-primary btn-xs" do %>
						<span class="glyphicon glyphicon-edit"></span>
					<% end %>
					<%= link_to(party, method: :delete, title: "Remover", 
										class: "btn btn-danger btn-xs", 
										data: { confirm: "Deseja remover?" }) do %>
						<span class="glyphicon glyphicon-remove"></span>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/parties/edit.html.erb
<% provide(:title, 'Editar Grupo') %>
<% provide(:label, 'Grupos') %>
<% provide(:button_text, 'Salvar') %>

<div class="row-fluid">
	<%= render 'form' %>
</div>

app/views/parties/index.html.erb
<% provide(:title, 'Grupos') %>
<% provide(:label, 'Grupos') %>

<div class="row">
	<%= render @parties %>
</div>

<div class="row">
	<div class="col-md-12">
		<%= link_to 'Novo Grupo', new_party_path, class: "btn btn-default btn-sm" %>
	</div>
</div>

app/views/parties/new.html.erb
<% provide(:title, 'Criar novo Grupo') %>
<% provide(:label, 'Grupos') %>
<% provide(:button_text, 'Criar') %>

<div class="row-fluid">
	<%= render 'form' %>
</div>

app/views/parties/show.html.erb
<% provide(:title, "#{@party.id} - #{@party.title}") %>
<% provide(:label, "Grupos") %>

<div class="row">

	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4><%= "#{@party.id} - #{@party.title}" %></h4>
			</div>

			<div class="panel-body">
				<% @party.members.each do |p| %>
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
						<div class="thumbnail">
							<%= link_to p.npc do %>
								<%= image_tag p.npc.img_url, size: "48", 
																							class: "img-thumbnail" %>
								<center>
									<%= p.npc.name %> <span class="badge"><%= p.amount %></span>
								</center>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>

			<div class="panel-footer">
				<% if current_user?(@party.user) || admin? %>
					<%= link_to 'Editar', edit_party_path(@party), 
																						class: "btn btn-primary btn-sm" %>
				<% end %>																			
				<%= link_to 'Voltar', parties_path, class: "btn btn-default btn-sm" %>
			</div>
		</div>
	</div>
</div>