config/routes.rb
Rails.application.routes.draw do

	root   'main#index'
	get    'main/index'
	get    'index'	      => 'main#index'
	get    'help'	        => 'main#help'
	get    'about'	      => 'main#about'
	get    'contact'      => 'main#contact'
	get    'battle'       => 'main#battle'
	post   'send_contact' => 'main#send_contact'
	get    'signup'	      => 'users#new'
	get    'login'	      => 'sessions#new'
	post   'login'	      => 'sessions#create'
	delete 'logout'	      => 'sessions#destroy'
	resources :users
	resources :weapons
	resources :skills
	resources :npcs
	resources :parties
	resources :weapon_categories

	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :npcs do
		resources :skills,      only: :index,   as: :skills
		resources :npc_weapons, only: :destroy, as: :equipments
	end
	resources :parties do
		resources :npcs,       only: :index,             as: :npcs
		resources :party_npcs, only: [:index, :destroy], as: :members
	end
	resources :relationships, only: [:create, :destroy]

end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
	belongs_to :user
	belongs_to :weapon_category
	has_many :npc_weapons
	has_many :npcs, through: :npc_weapons
	has_many :activity_feeds
	validates :name, presence: true, length: { maximum: 50 }
	validates :damage, presence: true
	validates :edge,   presence: true
	validates :injury, presence: true
	validates :weapon_category, presence: true

	def self.all_active
		all.where(deleted: false)
	end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
	before_action :set_weapon,     only: [:show,:edit,:update,:destroy]
	before_action :logged_in_user, only: [:index,:show,:edit,:update,:destroy]
	before_action :correct_user,   only: [:edit,:update,:destroy]

	def index
		@weapons = Weapon.all_active
	end

	def show
	end

	def new
		@weapon = Weapon.new
	end

	def create
		@weapon = Weapon.new(weapon_params)
		@weapon.user = current_user
		if @weapon.save
			current_user.generate_feed(weapon: @weapon, feed_type: 'insertion')
			flash[:success] = "Operação concluída com sucesso!"
			redirect_to @weapon
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @weapon.update_attributes(weapon_params)
			flash[:success] = "Informações atualizadas"
			current_user.generate_feed(weapon: @weapon, feed_type: 'updated')
			redirect_to @weapon
		else
			render 'edit'
		end
	end

	def destroy
		current_user.generate_feed(weapon: @weapon, feed_type: 'destroyed')
		@weapon.update(deleted: true, deleted_at: Time.zone.now)
		flash[:success] = "Operação concluída com sucesso!"
		redirect_to weapons_url
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_weapon
			@weapon = Weapon.find(params[:id])
		end

		def weapon_params
			params.require(:weapon).permit(:name, :damage, :edge, :injury, 
																			:weapon_category_id)
		end

		# Before filters

		# Confirms a logged-in user.
		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "Acesse o sistema para efetuar esta operação"
				redirect_to login_url
			end
		end

		# Confirms the correct user.
		def correct_user
			@weapon = Weapon.find(params[:id])
			redirect_to(root_url) unless current_user?(@weapon.user) || admin?
		end
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/weapons/_form.html.erb
<%= form_for(@weapon, class: 'form-horizontal') do |f| %>
	<div class="col-md-12">
		<div class="form-group">
			<%= render partial: 'shared/error_messages', locals: {object: @weapon} %>
		</div>
	</div>

	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h5>Informações</h5>
			</div>
			<div class="panel-body">
				<div class="col-md-12">
					<div class="form-group">
						<%= f.label :name, "Nome" %>
						<%= f.text_field :name, class: 'form-control input-sm' %>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<%= f.label :weapon_category_id, "Categoria" %>
						<%= f.collection_select :weapon_category_id, WeaponCategory.all, 
									:id, :name, {}, class: "form-control input-sm" %>
					</div>
				</div>

				<div class="col-md-2">
					<div class="form-group">
						<%= f.label :damage, "Dano" %>
						<%= f.number_field :damage, in: 1..25, step: 1, 
													class: 'form-control input-sm' %>
					</div>
				</div>

				<div class="col-md-2">
					<div class="form-group">
						<%= f.label :edge, "Gume" %>
						<%= f.number_field :edge, in: 0..11, step: 1, 
													class: 'form-control input-sm' %>
					</div>
				</div>

				<div class="col-md-2">
					<div class="form-group">
						<%= f.label :injury, "Trauma" %>
						<%= f.number_field :injury, in: 0..20, step: 1, 
													class: 'form-control input-sm' %>
					</div>
				</div>

			</div>
			<div class="panel-footer">
				<%= button_tag yield(:button_text),	type: :submit, 
																				class: "btn btn-default btn-sm" %>
			</div>
		</div>
	</div>
<% end %>

app/views/weapons/_weapon.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h5>
				<b><%= link_to "#{weapon.id} - #{weapon.name}", weapon %></b>
			</h5>
		</div>

		<div class="table-responsive">
			<table class="table table-condensed">
				<thead>
					<tr>
						<th>Dano</th>
						<th>Gume</th>
						<th>Trauma</th>
						<th>Ataque direcionado</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= weapon.damage %></td>
						<td><%= weapon.edge %></td>
						<td><%= weapon.injury %></td>
						<td><%= weapon.weapon_category.effect %></td>
					</tr>
				</tbody>
			</table>
		</div>

		<div class="panel-footer">
			<%= link_to weapon, title: "Visualizar", 
								class: "btn btn-default btn-xs" do %>
				<span class="glyphicon glyphicon-new-window"></span> Visualizar
			<% end %>
			<% if current_user?(weapon.user) || admin? %>
				<div class="pull-right">
					<%= link_to edit_weapon_path(weapon), title: "Editar", 
										class: "btn btn-primary btn-xs" do %>
						<span class="glyphicon glyphicon-edit"></span>
					<% end %>
					<%= link_to(weapon, method: :delete, title: "Remover", 
										class: "btn btn-danger btn-xs", 
										data: { confirm: "Deseja remover?" }) do %>
						<span class="glyphicon glyphicon-remove"></span>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/weapons/edit.html.erb
<% provide(:title, 'Editar') %>
<% provide(:label, 'Armas') %>
<% provide(:button_text, 'Salvar') %>

<div class="row-fluid">
	<%= render 'form' %>
</div>

app/views/weapons/index.html.erb
<% provide(:title, 'Armas') %>
<% provide(:label, 'Armas') %>

<div class="row">
	<%= render @weapons %>
</div>
<div class="row">
	<div class="col-md-12">
		<%= link_to 'Nova arma', new_weapon_path, class: "btn btn-default btn-sm" %>
	</div>
</div>

app/views/weapons/new.html.erb
<% provide(:title, 'Criar nova Arma') %>
<% provide(:label, 'Armas') %>
<% provide(:button_text, 'Criar') %>

<div class="row-fluid">
	<%= render 'form' %>
</div>

app/views/weapons/show.html.erb
<% provide(:title, "#{@weapon.id} - #{@weapon.name}") %>
<% provide(:label, 'Armas') %>
<% category = @weapon.weapon_category %>

<div class="row-fluid">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4><%= "#{@weapon.id} - #{@weapon.name} (#{category.name})" %></h4>
		</div>

		<div class="panel-body">
			<div class="col-md-12">
				<div class="col-md-3">
					<label class="text-right">Nome:</label>
				</div>
				<div class="col-md-9">
					<%= @weapon.name %>
				</div>
			</div>

			<div class="col-md-12">
				<div class="col-md-3">
					<label class="text-right">Dano:</label>
				</div>
				<div class="col-md-9">
					<%= @weapon.damage %>
				</div>
			</div>

			<div class="col-md-12">
				<div class="col-md-3">
					<label class="text-right">Gume:</label>
				</div>
				<div class="col-md-9">
					<%= @weapon.edge %>
				</div>
			</div>

			<div class="col-md-12">
				<div class="col-md-3">
					<label class="text-right">Trauma:</label>
				</div>
				<div class="col-md-9">
					<%= @weapon.injury %>
				</div>
			</div>

			<div class="col-md-12">
				<div class="col-md-3">
					<label class="text-right">Ataque direcionado:</label>
				</div>
				<div class="col-md-9">
					<%= category.effect %>
				</div>
			</div>
		</div>

		<div class="panel-footer">
			<% if current_user?(@weapon.user) || admin? %>
				<%= link_to 'Editar', edit_weapon_path(@weapon), 
																					class: "btn btn-primary btn-sm" %>
			<% end %>
			<%= link_to 'Voltar', weapons_path, class: "btn btn-default btn-sm" %>
		</div>
	</div>
</div>