config/routes.rb
Rails.application.routes.draw do

	root   'main#index'
	get    'main/index'
	get    'index'	      => 'main#index'
	get    'help'	        => 'main#help'
	get    'about'	      => 'main#about'
	get    'contact'      => 'main#contact'
	get    'battle'       => 'main#battle'
	post   'send_contact' => 'main#send_contact'
	get    'signup'	      => 'users#new'
	get    'login'	      => 'sessions#new'
	post   'login'	      => 'sessions#create'
	delete 'logout'	      => 'sessions#destroy'
	resources :users
	resources :weapons
	resources :skills
	resources :npcs
	resources :parties
	resources :weapon_categories

	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :npcs do
		resources :skills,      only: :index,   as: :skills
		resources :npc_weapons, only: :destroy, as: :equipments
	end
	resources :parties do
		resources :npcs,       only: :index,             as: :npcs
		resources :party_npcs, only: [:index, :destroy], as: :members
	end
	resources :relationships, only: [:create, :destroy]

end

app/models/npc.rb
class Npc < ActiveRecord::Base
	belongs_to :user
	has_many :equipments, class_name: "NpcWeapon", inverse_of: :npc, 
		:dependent => :destroy
	has_many :weapons, through: :npc_weapons
	has_many :npc_skills
	has_many :skills,  through: :npc_skills
	has_many :party_npcs
	has_many :parties, through: :party_npcs
	has_many :activity_feeds
	accepts_nested_attributes_for :equipments, :allow_destroy => true
	before_save { self.img_url = 'no_image' unless !self.img_url.empty? }

	validates :name,        presence: true, length: { maximum: 50 }
	validates :attr_index,  presence: true, numericality: { only_integer: true }
	validates :resource,    presence: true, numericality: { only_integer: true }
	validates :armour,      presence: true, numericality: { only_integer: true }
	validates :parry,       presence: true, numericality: { only_integer: true }
	validates :personality, presence: true, numericality: { only_integer: true }
	validates :movement,    presence: true, numericality: { only_integer: true }
	validates :perception,  presence: true, numericality: { only_integer: true }
	validates :survival,    presence: true, numericality: { only_integer: true }
	validates :custom,      presence: true, numericality: { only_integer: true }
	validates :vocation,    presence: true, numericality: { only_integer: true }
	validates_inclusion_of :attr_index,  in: 1..12
	validates_inclusion_of :resource,    in: 2..5
	validates_inclusion_of :armour,      in: 1..6
	validates_inclusion_of :parry,       in: 2..5
	validates_inclusion_of :personality, in: 1..3
	validates_inclusion_of :movement,    in: 1..3
	validates_inclusion_of :perception,  in: 1..3
	validates_inclusion_of :survival,    in: 1..3
	validates_inclusion_of :custom,      in: 1..3
	validates_inclusion_of :vocation,    in: 1..3

	def self.search(term)
	  where('LOWER(name) LIKE :term', term: "%#{term.downcase}%")
	end

	def filter_weapons
		Weapon.all_active
	end

	def filter_skills
		Skill.all_active
	end

	def build_equipments
		self.equipments.build.bonus = 1 unless !self.equipments.empty?
	end

	def self.all_active
		all.where(deleted: false)
	end

	def self.newest
		all.where(deleted: false).select(:id, :name, :description, :img_url)
			.order(created_at: :desc).limit(3)
	end

	# Cria o vinculo entre o npc e as habilidades, deleta anteriores
	def create_skills(skills)
		self.npc_skills.destroy_all
		skills.each do |skill|
			if !skill.empty?
			 	self.npc_skills.create({skill_id: skill.to_i})
			end
		end
	end
end

app/controllers/npcs_controller.rb
class NpcsController < ApplicationController
	before_action :set_npc,        only: [:show, :edit, :update, :destroy]
	before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
	before_action :correct_user,	 only: [:correct_user, :edit, :update, :destroy]

	def index
		if params[:party_id]
			@npcs = Party.find(params[:party_id]).npcs
			respond_to do |format|
				format.html
				format.json { 
					render :json => @npcs.to_json(:include => { 
						:equipments => { 
							:only    => [:weapon, :bonus],
							:include => { 
								:weapon  => { 
									:only    => [:name, :damage, :damage, :edge, :injury],
									:include => {
										:weapon_category => {
											:only    => [:name, :effect]
										}
									}
								}
							}
						}
					}
				)}
			end
		elsif params[:term]
			respond_to do |format|
				format.html
				format.json { @npcs = Npc.search(params[:term]) }
			end
		else
			@npcs = Npc.all_active
			@newest = Npc.newest
		end
	end

	def show
		respond_to do |format|
			format.html
			format.json { 
				render :json => @npc.to_json(:include => { 
					:equipments => { 
						:only    => [:weapon, :bonus],
						:include => { 
							:weapon  => { 
								:only    => [:name, :damage, :damage, :edge, :injury],
								:include => {
									:weapon_category => {
										:only    => [:name, :effect]
									}
								}
							}
						}
					}
				}
			)}
		end
	end

	def new
		@npc = Npc.new
		@npc.build_equipments
	end

	def create
		@npc = Npc.new(npc_params)
		@npc.user = current_user
		if @npc.save
			current_user.generate_feed(npc: @npc, feed_type: 'insertion')
			@npc.create_skills(params[:npc][:skills])
			flash.now[:success] = COOL_SUCCESS_MESSAGE
			redirect_to @npc and return
		else
			flash.now[:danger] = COOL_ERROR_MESSAGE
		end
		render :action => 'new'
	end

	def edit
	end

	def update
		# save goes like usual
		if @npc.update_attributes(npc_params)
			@npc.create_skills(params[:npc][:skills])
			current_user.generate_feed(npc: @npc, feed_type: 'updated')
			flash[:success] = COOL_SUCCESS_MESSAGE
			redirect_to @npc and return
		else
			flash.now[:danger] = COOL_ERROR_MESSAGE
		end
		render :action => 'edit'
	end

	def destroy
		current_user.generate_feed(npc: @npc, feed_type: 'destroyed')
		@npc.update(deleted: true, deleted_at: Time.zone.now)
		flash.now[:success] = "Operação concluída com sucesso!"
		redirect_to npcs_url
	end

	private

		# Use callbacks to share common setup or constraints between actions.
		def set_npc
			@npc = Npc.find(params[:id])
		end

		def npc_params
			params.require(:npc).permit(:name, :description, :img_url, :ally, 
				:attr_index, :resistance, :resource, :parry, :armour, 
				:personality, :movement, :perception, :survival, :custom, :vocation, 
				equipments_attributes: [:id, :weapon_id, :bonus, :_destroy])
		end

		# Before filters

		# Confirms a logged-in user.
		def logged_in_user
			unless logged_in?
				store_location
				flash.now[:danger] = "Acesse o sistema para efetuar esta operação"
				redirect_to login_url
			end
		end

		# Confirms the correct user.
		def correct_user
			redirect_to(root_url) unless current_user?(@npc.user) || admin?
		end
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/views/npcs/_form.html.erb
<%= form_for(@npc, id: "npc_form", class: 'form-horizontal') do |f| %>
	<div class="row">
		<div class="col-md-12">
			<%= render partial: 'shared/error_messages', locals: {object: @npc} %>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading"><h5>Dados Básicos</h5></div>
					<div class="panel-body">
						<div class="col-md-12">
							<div class="form-group">
								<%= f.label :name, "Nome", class: 'col-md-12' %>
								<%= f.text_field :name, placeholder: "Ex: Etevaldo",
																						class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-12">
							<div class="form-group">
								<%= f.label :img_url, "URL Ilustração", class: 'col-md-12' %>
								<%= f.text_field :img_url, 
																		placeholder: "Ex: http://goo.gl/LGWwUZ",
																						class: 'form-control input-sm' %>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading"><h5>Informações</h5></div>
					<div class="panel-body">
						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :ally, "Aliado", class: 'col-md-12' %>
								<%= f.select(:ally, [['Sim', true],['Não', false]], {}, 
																				{ class: 'form-control input-sm' }) %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :attr_index, "Ind. Atributo", 
																												class: 'col-md-12' %>
								<%= f.number_field :attr_index, in: 1..12, step: 1, 
															class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :resistance, "Resitência", class: 'col-md-12' %>
								<%= f.number_field :resistance, in: 0..100, step: 1, 
															class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :resource, "Recurso", class: 'col-md-12' %>
								<%= f.number_field :resource, in: 2..5, step: 1, value: 2,
															class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :parry, "Aparar", class: 'col-md-12' %>
								<%= f.number_field :parry, in: 2..5, step: 1, value: 2,
															class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :armour, "Armadura", class: 'col-md-12' %>
								<%= f.number_field :armour, in: 1..6, step: 1, 
															class: 'form-control input-sm' %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<!-- Perícias -->
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading"><h5>Perícias</h5></div>
					<div class="panel-body">
						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :personality, "Personalidade", class: 'col-md-12' %>
								<%= f.number_field :personality, in: 1..3, step: 1, 
																							class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :movement, "Movimento", class: 'col-md-12' %>
								<%= f.number_field :movement, in: 1..3, step: 1, 
																							class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :perception, "Percepção", class: 'col-md-12' %>
								<%= f.number_field :perception, in: 1..3, step: 1, 
																							class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :survival, "Sobrevivência", class: 'col-md-12' %>
								<%= f.number_field :survival, in: 1..3, step: 1, 
																							class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :custom, "Costumes", class: 'col-md-12' %>
								<%= f.number_field :custom, in: 1..3, step: 1, 
																							class: 'form-control input-sm' %>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<%= f.label :vocation, "Ocupação", class: 'col-md-12' %>
								<%= f.number_field :vocation, in: 1..3, step: 1, 
																							class: 'form-control input-sm' %>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Fim Perícias -->

			<div class="col-md-6">
				<div class="panel panel-default" id="weapons">
					<div class="panel-heading">
						<h5>Equipamentos</h5>
					</div>

					<div class="table-reponsive">
						<table class="table table-condensed">
							<thead>
								<tr>
									<th width="8%"></th>
									<th width="72%">Arma</th>
									<th width="20%">Bonus</th>
								</div>
							</thead>
							<tbody>
								<%= f.fields_for :equipments, @npc.equipments do |ff| %>
									<tr class="duplicatable">
										<%= ff.hidden_field :id, class: 'nested_id' %>
										<td align="center">
											<% if ff.object.new_record? %>
												<%= link_to '', remote: true, 
															class: 'btn btn-danger btn-xs destroy_dup' do %>
													<%= link_icon('minus') %>
												<% end %>
											<% else %>
												<%= link_to npc_equipment_path(@npc, ff.object), 
																method: :delete, remote: true, 
																class: 'btn btn-danger btn-xs destroy_dup' do %>
													<%= link_icon('minus') %>
												<% end %>
											<% end %>
										</td>
										<td>
											<%= ff.collection_select :weapon_id, @npc.filter_weapons, 
														:id, :name, {}, class: "form-control input-sm" %>
										</td>
										<td>
											<%= ff.number_field :bonus, 
																					class: "form-control input-sm" %>
										</td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>

					<div class="panel-footer">
						<%= link_to '', class: 'btn btn-info btn-xs duplicate' do %>
							<%= link_icon('plus') %> Adicionar
						<% end %>
					</div>
				</div>
			</div>
			
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading"><h5>Habilidades</h5></div>
					<div class="panel-body">
						<div class="form-group">
							<%= f.collection_select(:skills, @npc.filter_skills, :id, :name, 
								{selected: @npc.skill_ids, include_blank: false, prompt: false}, 
								multiple: true, class: "form-control input-sm")	%>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h5>Descrição</h5>
			</div>
			<div class="panel-body">
				<%= f.text_area :description, size: "30x6", 
																			class: 'form-control input-sm' %>
			</div>
		</div>
	</div>

	<div class="col-md-12">
		<div class="form-group">
			<%= button_tag yield(:button_text),	type: :submit, 
																						class: "btn btn-default btn-sm" %>
		</div>
	</div>
<% end %>

app/views/npcs/_no_image.html.erb
<%= content_tag :div,  class: "img-thumbnail fake_img" do %>
	Sem imagem
<% end %>

app/views/npcs/_npc.html.erb
<% ally_class = npc.ally ? 'success' : 'danger' %>
<% perc_attr_index = (npc.attr_index*100) / 12 %>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
	<div class="panel panel-default">
		<div class="panel-heading">
			<p>
				<b class="text-<%= ally_class %>">
					<span class="badge"><%= npc.id %></span> <%= npc.name %> 
					<span class="pull-right">
						<%= bool_icon(npc.ally, false,
															yes_icon: "eye-open", no_icon: "eye-close") %>
					</span>
				</b>
			</p>
		</div>

		<%= link_to npc do %>
			<%= image_tag npc.img_url, size: "300", class: "img-thumbnail" %>
		<% end %>

		<ul class="list-group">
			<li class="list-group-item list-group-item-small">
				<b>Indice de Atributo</b>
				<div class="progress">
					<div class="progress-bar progress-bar-<%= ally_class %>" 
							role="progressbar" aria-valuemin="0" aria-valuemax="12" 
							aria-valuenow="<%= npc.attr_index %>"
						 	style="width: <%= perc_attr_index %>%;">
						<%= npc.attr_index %>
					</div>
				</div>
			</li>
			<li class="list-group-item list-group-item-small">
				<center><b>Criado por:</b> <%=  npc.user.name %></center>
			</li>
		</ul>

		<div class="panel-footer">
			<%= link_to npc, title: "Visualizar", 
														class: "btn btn-default btn-xs" do %>
				<%= link_icon "new-window","Visualizar" %>
			<% end %>
			<% if current_user?(npc.user) || admin? %>
				<div class="pull-right">
					<%= link_to edit_npc_path(npc), title: "Editar", 
										class: "btn btn-primary btn-xs" do %>
						<span class="glyphicon glyphicon-edit"></span>
					<% end %>
					<%= link_to(npc, method: :delete, title: "Remover", 
										class: "btn btn-danger btn-xs", 
										data: { confirm: "Deseja remover?" }) do %>
						<span class="glyphicon glyphicon-remove"></span>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/npcs/edit.html.erb
<% provide(:title, 'Editar') %>
<% provide(:label, 'Modificar informações') %>
<% provide(:button_text, 'Salvar') %>

<div class="row">
	<%= render 'form' %>
</div>

<script type="text/javascript">
	$(function() {
		$.startMultiselects();
	});
</script>

app/views/npcs/index.html.erb
<% provide(:title, 'Npcs') %>
<% provide(:label, 'Npcs') %>

<div class="row">
	<div class="col-md-12">
		<h4 class="epic-title"><b>Recentes</b></h4>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="carousel-mini">
			<div id="carousel-npcs" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators">
					<% @newest.each_with_index do |n, index| %>
						<li data-target="#carousel-npcs" 
								data-slide-to="<%= index %>" 
								class="<%= index == 0 ? 'active' : '' %>"></li>
					<% end %>
				</ol>

				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<% @newest.each_with_index do |n, index| %>
						<div class="item <%= index == 0 ? 'active' : '' %>">
							<%= link_to n do %>
								<center>
									<%= image_tag n.img_url, size: "300",  
																						class: "img-thumbnail" %>
								</center>
								<div class="carousel-caption">
									<h3><%= n.name %></h3>
									<p><small><%= slice_text(n.description, 100) %></small></p>
								</div>
							<% end %>
						</div>
					<% end %>
				</div>

				<!-- Controls -->
				<a class="left carousel-control" href="#carousel-npcs" 
						role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" 
						aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#carousel-npcs" 
						role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" 
						aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<h4 class="epic-title"><b>Outros npcs</b></h4>
	</div>
</div>
<div class="row">
	<%= render @npcs %>
</div>

<div class="row">
	<div class="col-md-12">
		<%= link_to 'Novo NPC', new_npc_path, class: "btn btn-default btn-sm" %>
	</div>
</div>

app/views/npcs/index.js.erb
$(function() {
	alert('teste');
});

app/views/npcs/new.html.erb
<% provide(:title, 'Criar novo NPC') %>
<% provide(:label, 'Criar novo NPC') %>
<% provide(:button_text, 'Criar') %>

<div class="row">
	<%= render 'form' %>
</div>

<script type="text/javascript">
	$(function() {
		$.startMultiselects();
	});
</script>

app/views/npcs/show.html.erb
<% provide(:title, "#{@npc.id} - #{@npc.name}") %>
<% provide(:label, "Npcs") %>

<div class="row">

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h5><%= "#{@npc.id} - #{@npc.name}" %></h5>
			</div>

			<%= image_tag @npc.img_url, size: "200", class: "img-thumbnail" %>

			<div class="panel-body">
				<p><%= @npc.description %></p>
			</div>

			<div class="panel-footer">
				<% if current_user?(@npc.user) || admin? %>
					<%= link_to 'Editar', edit_npc_path(@npc), 
																					class: "btn btn-primary btn-sm" %>
				<% end %>
				<%= link_to 'Voltar', npcs_path, class: "btn btn-default btn-sm" %>
			</div>
		</div>
	</div>

	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h5>Informações</h5>
			</div>

			<div class="panel-body panel-columns text-center">

				<div class="row-fluid">
					<div class="col-md-6 col-header">
						<b>Aliado</b>
					</div>
					<div class="col-md-6 col-header">
						<b>Nível de Atributo</b>
					</div>
				</div>
				<div class="row-fluid">
					<div class="col-md-6">
						<%= @npc.ally %>
					</div>
					<div class="col-md-6">
						<%= @npc.attr_index %>
					</div>
				</div>

				<div class="row-fluid">
					<div class="col-md-6 col-header">
						<b>Resistência</b>
					</div>
					<div class="col-md-6 col-header">
						<b>Recurso</b>
					</div>
				</div>
				<div class="row-fluid">
					<div class="col-md-6">
						<%= @npc.resistance %>
					</div>
					<div class="col-md-6">
						<%= @npc.resource %>
					</div>
				</div>

				<div class="row-fluid">
					<div class="col-md-6 col-header">
						<b>Aparar</b>
					</div>
					<div class="col-md-6 col-header">
						<b>Armadura</b>
					</div>
				</div>
				<div class="row-fluid">
					<div class="col-md-6">
						<%= @npc.parry %>
					</div>
					<div class="col-md-6">
						<%= @npc.armour %>
					</div>
				</div>

				<div class="row-fluid">
					<div class="col-md-12 col-header">
						<b>Perícias</b>
					</div>
				</div>
				<div class="row-fluid">
					<div class="col-md-6">
						<b>Personalidade:</b> <%= @npc.personality %>
					</div>
					<div class="col-md-6">
						<b>Sobrevivência:</b> <%= @npc.survival %>
					</div>
				</div>
				<div class="row-fluid">
					<div class="col-md-6">
						<b>Movimento:</b> <%= @npc.movement %>
					</div>
					<div class="col-md-6">
						<b>Costumes:</b> <%= @npc.custom %>
					</div>
				</div>
				<div class="row-fluid">
					<div class="col-md-6">
						<b>Percepção:</b> <%= @npc.perception %>
					</div>
					<div class="col-md-6">
						<b>Ocupação:</b> <%= @npc.vocation %>
					</div>
				</div>

				<div class="row-fluid">
					<div class="col-md-12 col-header">
						<b>Perícias com Armas</b>
					</div>
				</div>
				<% @npc.equipments.each do |equipment| %>
					<div class="row-fluid">
						<div class="col-md-6 text-right">
							<%= link_to equipment.weapon.name, equipment.weapon %>
						</div>
						<div class="col-md-6 text-left">
							<%= equipment.bonus %>
						</div>
					</div>
				<% end %>

				<div class="row-fluid">
					<div class="col-md-12 col-header">
						<b>Habilidades Especiais</b>
					</div>
				</div>
				<div class="row-fluid">
					<% @npc.skills.each do |skill| %>
						<div class="col-md-6">
							<%= link_to skill.name, skill %>
						</div>
					<% end %>
				</div>

				<div class="row-fluid">
					<div class="col-md-12 col-header">
						<b>Criado por:</b> <%=  @npc.user.name %>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>