config/routes.rb
Rails.application.routes.draw do

	root   'main#index'
	get    'main/index'
	get    'index'	      => 'main#index'
	get    'help'	        => 'main#help'
	get    'about'	      => 'main#about'
	get    'contact'      => 'main#contact'
	get    'battle'       => 'main#battle'
	post   'send_contact' => 'main#send_contact'
	get    'signup'	      => 'users#new'
	get    'login'	      => 'sessions#new'
	post   'login'	      => 'sessions#create'
	delete 'logout'	      => 'sessions#destroy'
	resources :users
	resources :weapons
	resources :skills
	resources :npcs
	resources :parties
	resources :weapon_categories

	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :npcs do
		resources :skills,      only: :index,   as: :skills
		resources :npc_weapons, only: :destroy, as: :equipments
	end
	resources :parties do
		resources :npcs,       only: :index,             as: :npcs
		resources :party_npcs, only: [:index, :destroy], as: :members
	end
	resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_header.html.erb
<nav class="navbar yamm navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" 
					data-toggle="collapse" data-target="#navbar" 
					aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<%= link_to(root_path) do %>
						<%= link_icon 'home' %> Principal
					<% end %>
				</li>
				<% if logged_in? %>
					<li class="dropdown yamm-fw">
						<a href="#" data-toggle="dropdown" class="dropdown-toggle">
							<%= link_icon 'th' %> Opções<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li>
								<!-- Content container to add padding -->
								<div class="yamm-content">
									<div class="row">
										<ul class="col-sm-3 list-unstyled">
											<li>
												<h5>
													<%= link_icon 'user' %> <strong>Membros</strong> 
												</h5>
											</li>
											<li><%= link_to "Listar", users_path   %></li>
											<li><%= link_to "Novo",   new_user_path %></li>
										</ul>
										<ul class="col-sm-3 list-unstyled">
											<li>
												<h5>
													<%= link_icon 'user' %> <strong>Npcs</strong>
												</h5>
											</li>
											<li><%= link_to "Visualizar", npcs_path    %></li>
											<li><%= link_to "Criar",      new_npc_path %></li>
										</ul>
										<ul class="col-sm-3 list-unstyled">
											<li>
												<h5><strong>Grupos</strong></h5>
											</li>
											<li><%= link_to "Visualizar", parties_path   %></li>
											<li><%= link_to "Criar",      new_party_path %></li>
										</ul>
										<ul class="col-sm-3 list-unstyled">
											<li>
												<h5><strong>Armas</strong></h5>
											</li>
											<li><%= link_to "Todas", weapons_path    %></li>
											<li><%= link_to "Criar", new_weapon_path %></li>
											<li>
												<%= link_to "Categorias", weapon_categories_path %>
											</li>
										</ul>
										<ul class="col-sm-3 list-unstyled">
											<li>
												<h5><strong>Habilidades</strong></h5>
											</li>
											<li><%= link_to "Todas", skills_path    %></li>
											<li><%= link_to "Criar", new_skill_path %></li>
										</ul>
									</div>
								</div><!-- Content container to add padding -->
							</li>
						</ul>
					</li>
					<li>
						<%= link_to "Batalha", battle_path %>
					</li>
				<% end %>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if logged_in? %>
					<li class="dropdown active">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" 
								role="button" aria-haspopup="true" aria-expanded="false">
							<%= gravatar_for current_user, size: 22, classes: "img-circle" %> 
							<span class="<%= admin? ? 'text-warning' : '' %>">
								<%= current_user.name %>
							</span> 
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Minha conta", current_user %></li>
							<li><%= link_to "Opções", edit_user_path(current_user) %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to 'Sobre o sistema', about_path %></li>
							<!-- <li><%#= link_to 'Contato', contact_path %></li> -->
							<!-- <li><%#= link_to 'Ajuda',	 help_path %></li> -->
							<li role="separator" class="divider"></li>
							<li>
								<%= link_to logout_path, method: "delete" do %>
									<span class="glyphicon glyphicon-log-out"></span> Sair
								<% end %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to 'Sobre', about_path %></li>
					<!-- <li><%#= link_to 'Contato', contact_path %></li> -->
					<!-- <li><%#= link_to 'Ajuda',   help_path    %></li> -->
					<li class="active">
						<%= link_to 'Entrar',	login_path %>
					</li>
				<% end %>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    'application', media: 'all', 
																						'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', params[:controller] %>
	<%= csrf_meta_tags %>
</head>
	<body class="<%= controller_name %> <%= action_name %>">
		<%= render 'layouts/header' %>
		<div class="container">
			<% if !yield(:label).empty? %>
				<div class="page-header">
					<h3><%= yield(:label) %></h3>
				</div>
			<% end %>

			<% flash.each do |message_type, message| %>
				<div class="alert alert-<%= message_type %>">
					<button type="button" data-dismiss="alert" class="close">
						<span class="glyphicon glyphicon-remove"></span>
					</button>
					<%= message %>
				</div>
			<% end %>
			<%= yield %>

			<%= debug(params) if Rails.env.development? %>
			<footer class="footer">
				The One Ring Tools. Desenvolvido por: Kaciano Ghelere - 2016<br/>
				Todos os direitos de imagens, fontes e regras do sistema reservados 
				aos respectivos criadores
			</footer>
		</div>
	</body>
</html>